image: node:22

stages:
  - install
  - test_karma
  - test_pw
  - build

cache:
  key: node-modules
  paths:
    - node_modules/

install:
  stage: install
  script:
    - npm ci
    - echo "Dependencies installed"

.test_karma:
  stage: test_karma
  script:
    - npm run test -- --watch=false --browsers=ChromeHeadless
  artifacts:
    when: always
    reports:
      junit: test-results/karma-results.xml
  allow_failure: false

.test_e2e:
  stage: test_pw
  script:
    - npx playwright install --with-deps
    - npm run build
    - npx playwright test
  artifacts:
    when: always
    paths:
      - playwright-report/
      - test-results/
  allow_failure: false

build:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - dist/
