stages:
  - install
  - test_karma
  - test_pw
  - build

image: node:18

cache:
  key: node-modules
  paths:
    - node_modules/

before_script:
  - npm ci

install:
  stage: install
  script:
    - echo "Dependencies are installed"

test:
  stage: test_karma
  script: npm run test -- --watch=false --browsers=chromeHeadless
  artifacts:
    when: always
    reports:
      junit: test-result/**/*.xml
  allow_failure: false

test_e2e:
  stage: test_pw
  script:
    - npm run build
  artifacts:
    paths:
      - dits/
